Use redux in react copmonents
rachaouldbabaali/bookstore pull request #3
Opened 2023-06-20 14:47 UTC by rachaouldbabaali

In this pull request, I have : 

- [ ] Used store, actions, and reducers in React.

- [ ] Connected React and Redux.
- [ ] Dispatched actions using useDispatch.
- [ ] added Remove and add buttons.

2023-06-20 15:07 UTC, julie-ify requested changes
## Hi @rachaouldbabaali,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 15:07 UTC, julie-ify commented on src/redux/books/booksSlice.js
> +  ],
- [ ] I can not delete the initial books, but I can remove the ones I added. Kindly fix that. Instead of `item_id: uuidv4()`, based on your store, you should use:

  ```
  id: uuidv4()
  ```

2023-06-20 15:13 UTC, rachaouldbabaali commented
Thank you @julie-ify ,  I truly appreciate your time and efforts in reviewing my work, issue has been fixed 😃

2023-06-20 15:22 UTC, levy002 approved these changes
## Hello @rachaouldbabaali 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## HIghlights
- No linter error :heavy_check_mark: 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 07:24 UTC, rachaouldbabaali commented
Thank you,  I truly appreciate your time and efforts in reviewing my work, 😃

2023-06-21 07:24 UTC, merged